spring.datasource.url=jdbc:postgresql://postgresql_container:5432/portfolio
spring.datasource.username=sammit
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
server.port=8080
spring.cache.cache-names=projects
management.endpoints.web.exposure.include=*
spring.output.ansi.enabled=always


